server:
  port: 7001

spring:
  application:
    name: profile-service
  data:
    mongodb:
      database: CaseStudy-OnlineShoppingCart
      host: localhost
      port: 27017

#eureka:
#  instance:
#    hostname: localhost

eureka:
  client:
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7000/eureka
  instance:
    hostname: localhost

#keycloak:
#  realm: realm1
#  auth-server-url: http://127.0.0.1:8080
#  resource: springboot-keycloak
#  public-client: true
#  bearer-only: true
#  use-resource-role-mappings : true